"""
schemas.py - Pydantic request validation and response models for Authentication domain.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict


class UserAuthResponse(BaseModel):
    """
    Standard response model for successful authentication actions (register/login).
    Never includes password or hash data.
    """
    clerk_user_id: str
    username: Optional[str] = None
    message: str
    sign_in_token: Optional[str] = Field(default=None, description="Clerk sign-in ticket for client session activation")


class UserInfoResponse(BaseModel):
    """
    Response model for user status check endpoint.
    Indicates whether user exists and if they have facial recognition enabled.
    """
    clerk_user_id: str
    username: Optional[str] = None
    created_at: datetime

    has_face_registered: bool
    face_count: Optional[int] = 0
    model_config = ConfigDict(from_attributes=True)


class FaceDescriptorResponse(BaseModel):
    """
    Response model for registered face metadata.
    Excludes the raw vector embedding.
    """
    id: int
    label: str
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)


class FaceRegisterRequest(BaseModel):
    """
    Schema for registering face descriptor vector for an existing user.
    face_descriptor is a 128-element float array generated by face-api.js.
    """
    clerk_user_id: Optional[str] = Field(default=None, description="Clerk user ID")
    username: Optional[str] = Field(default=None, description="Clerk user ID or legacy username")
    label: Optional[str] = Field(default=None, description="Optional custom label for the face")
    face_descriptor: list[float] = Field(..., description="128-length float array representing face biometric embedding")


class FaceLoginRequest(BaseModel):
    """
    Schema for facial recognition login attempt.
    face_descriptor is a 128-element float array extracted from webcam frame.
    """
    face_descriptor: list[float] = Field(..., description="128-length float array from webcam face capture")


class FaceUpdateRequest(BaseModel):
    """
    Schema for updating/re-registering face descriptor.
    Security verification is handled via Clerk session authentication.
    """
    clerk_user_id: Optional[str] = Field(default=None, description="Clerk user ID")
    username: Optional[str] = Field(default=None, description="Clerk user ID or legacy username")
    password: Optional[str] = Field(default=None, description="Legacy password field (ignored)")
    label: Optional[str] = Field(default=None, description="Optional custom label for the face")
    face_descriptor: list[float] = Field(..., description="128-length float array representing new face descriptor")


class MessageResponse(BaseModel):
    """
    Standard message response model.
    """
    message: str


class AccountDeletionResponse(BaseModel):
    """
    Response model for destructive account deletion.
    """
    message: str
    clerk_user_id: str
    deleted_faces_count: int
    deleted_documents_count: int
    deleted_sessions_count: int


__all__ = [
    "UserAuthResponse",
    "UserInfoResponse",
    "FaceDescriptorResponse",
    "FaceRegisterRequest",
    "FaceLoginRequest",
    "FaceUpdateRequest",
    "MessageResponse",
    "AccountDeletionResponse",
]
