"""
schemas.py - Pydantic request validation and response models.

Defines input validation schemas for API endpoints and output structures
for serialized HTTP JSON responses.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict


class UserRegisterRequest(BaseModel):
    """
    Schema for validating user registration input.
    - username: Must be 3-30 characters long and contain only letters, numbers, and underscores.
    - password: Must be at least 6 characters long.
    """
    username: str = Field(
        ...,
        min_length=3,
        max_length=30,
        pattern=r"^[a-zA-Z0-9_]+$",
        description="Username (3-30 chars, alphanumeric and underscores only)"
    )
    password: str = Field(
        ...,
        min_length=6,
        description="Password (minimum 6 characters)"
    )


class UserLoginRequest(BaseModel):
    """
    Schema for validating password login input.
    """
    username: str = Field(..., description="Registered username")
    password: str = Field(..., description="Account password")


class UserAuthResponse(BaseModel):
    """
    Standard response model for successful authentication actions (register/login).
    Never includes password or hash data.
    """
    username: str
    message: str


class UserInfoResponse(BaseModel):
    """
    Response model for user status check endpoint.
    Indicates whether user exists and if they have facial recognition enabled.
    """
    username: str
    created_at: datetime
    has_face_registered: bool

    model_config = ConfigDict(from_attributes=True)


class FaceRegisterRequest(BaseModel):
    """
    Schema for registering face descriptor vector for an existing user.
    face_descriptor is a 128-element float array generated by face-api.js.
    """
    username: str = Field(..., description="Registered username")
    face_descriptor: list[float] = Field(..., description="128-length float array representing face biometric embedding")


class FaceLoginRequest(BaseModel):
    """
    Schema for facial recognition login attempt.
    face_descriptor is a 128-element float array extracted from webcam frame.
    """
    face_descriptor: list[float] = Field(..., description="128-length float array from webcam face capture")


class FaceUpdateRequest(BaseModel):
    """
    Schema for updating/re-registering face descriptor.
    Requires password verification for security.
    """
    username: str = Field(..., description="Registered username")
    password: str = Field(..., description="Current password for verification")
    face_descriptor: list[float] = Field(..., description="128-length float array representing new face descriptor")


class MessageResponse(BaseModel):
    """
    Standard message response model.
    """
    message: str


class DocumentUploadResponse(BaseModel):
    """
    Response model returned after an uploaded file has been processed.
    Contains processing status, chunk count, AI summary (Prompt 8), and an informative message.
    """
    id: int
    filename: str
    status: str
    chunk_count: int = 0
    summary: Optional[str] = None
    message: str
    error_message: Optional[str] = None


class DocumentMetadataResponse(BaseModel):
    """
    Lightweight document metadata response model for document listings.
    Excludes full extracted text to keep responses lightweight and fast.
    Includes AI auto-summary (Prompt 8).
    """
    id: int
    original_filename: str
    file_type: str
    upload_timestamp: datetime
    status: str
    chunk_count: int = 0
    summary: Optional[str] = None
    error_message: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


# ==============================================================================
# CHAT & RAG QUERY SCHEMAS (PROMPT 7)
# ==============================================================================

class Citation(BaseModel):
    """
    Source citation grouped by document file, indicating format and matching chunk indexes.
    """
    filename: str
    file_type: str = "txt"
    chunk_references: List[int] = []
    document_id: Optional[int] = None


class ChatQueryRequest(BaseModel):
    """
    Schema for POST /chat/query request body.
    - username: Owner of the indexed documents (maintains tenant isolation).
    - query: Natural language question asked by the user.
    - document_ids: Optional list of SQLite document IDs to restrict search scope.
    """
    username: str = Field(..., description="Username querying the knowledge base")
    query: str = Field(..., min_length=1, description="Question or query string")
    document_ids: Optional[List[int]] = Field(
        default=None,
        description="Optional list of document IDs to filter the retrieval scope"
    )


class ChatQueryResponse(BaseModel):
    """
    Schema for POST /chat/query response body (Prompt 7).
    - answer: Polished user-facing answer or helpful fallback message.
    - is_fallback: True if answer is a fallback (not in document), False if answered from context.
    - citations: Source document citations grouped by filename with chunk indexes.
    - low_context: True if fewer than 2 chunks were retrieved for a non-fallback answer.
    """
    answer: str
    is_fallback: bool = False
    citations: List[Citation] = []
    low_context: bool = False


# ==============================================================================
# CHAT SESSION & MESSAGE PERSISTENCE SCHEMAS (PROMPT 9)
# ==============================================================================

class CreateSessionRequest(BaseModel):
    """
    Schema for POST /chat/sessions request body.
    """
    username: str = Field(..., description="Owner username for the chat session")


class SessionResponse(BaseModel):
    """
    Schema for session creation response.
    Returns session_id, id, title, and created_at.
    """
    session_id: int
    id: int
    title: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SessionItemResponse(BaseModel):
    """
    Schema for session list item in GET /chat/sessions/{username}.
    """
    id: int
    session_id: int
    title: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class MessageItemResponse(BaseModel):
    """
    Schema for message item returned in GET /chat/sessions/{session_id}/messages.
    """
    id: int
    session_id: int
    role: str
    content: str
    citations: Optional[List[Citation]] = None
    is_fallback: bool = False
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DeleteSessionRequest(BaseModel):
    """
    Schema for DELETE /chat/sessions/{session_id} body to confirm ownership.
    """
    username: str = Field(..., description="Username confirming ownership of session to delete")


class SessionMessageRequest(BaseModel):
    """
    Schema for POST /chat/sessions/{session_id}/message.
    """
    username: str = Field(..., description="Username sending the message")
    query: str = Field(..., min_length=1, description="User prompt or question")
    document_ids: Optional[List[int]] = Field(
        default=None,
        description="Optional list of document IDs to restrict retrieval scope"
    )


class SessionMessageResponse(BaseModel):
    """
    Schema for POST /chat/sessions/{session_id}/message response.
    Returns the assistant's message: answer, is_fallback, citations, low_context.
    """
    answer: str
    is_fallback: bool = False
    citations: List[Citation] = []
    low_context: bool = False
    is_error: bool = False


